---
title: "Work Practices and Perceptions from Women Core Developers in OSS Communities"
author: "Edna Canedo, Rodrigo Bonifácio, Márcio Okimoto, Alexander Serebrenik, Gustavo Pinto, and Eduardo Monteiro"
date: "ESEM 2020"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Supplementary material

### Survey Questions 

| **Question**                                                                                                      | **Details**                                                                                                                                                                                                                                                              |
| ----------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| 1. In what group age are you?                                                                                     | Closed question with options:<br><br>- 18 - 25 years old<br>- 26 - 30 years old<br>- 31 - 35 years old<br>- 36 - 40 years old<br>- 41 - 50 years old<br>- 51 - 60 years old<br>- 61 - 70 years old<br>- 71 + years old                                                   |
| 2. What is your workplace?                                                                                        | Open-ended question                                                                                                                                                                                                                                                      |
| 3. How long have you been contributing to OSS Communities?                                                        | Closed question with options:<br><br>- Under one year of experience<br>- More than one year and under four years of experience<br>- More than four years and under ten years of experience<br>- More than ten years of experience                                        |
| 4. What is your education level?                                                                                  | Closed question with options:<br><br>- Undergraduate Student<br>- Graduated<br>- Master Student<br>- Master<br>- PhD Student<br>- PhD                                                                                                                                    |
| 5. What programming languages do you dominate?                                                                    | Closed question with options:<br><br>- JavaScript<br>- PYTHON<br>- JAVA<br>- Ruby on Rails<br>- PHP<br>- C++<br>- CSS<br>- C#<br>- GO<br>- C<br>- TYPESCRIPT<br>- SHELL<br>- SWIFT<br>- SCALA<br>- OBJECTIVE-C                                                           |
| 6. What communication channel do you use to conduct your interactions with other team members in OSS Communities? | Closed question with options:<br><br>- E-mail<br>- Online chat<br>- Online file sharing<br>- Real-time doc editing<br>- Phone calling<br>- Email lists<br>- Social networking sites<br>- Code sharing systems<br>- Online discussion boards<br>- Online member directory |
| 7. How often do you usually interact with other team members in OSS Communities?                                  | Closed question with options:<br><br>- Always<br>- Very Often<br>- Sometimes<br>- Rarely<br>- Never                                                                                                                                                                      |
| 8. Are you happy with your participation in OSS Communities?                                                      | Closed question with options:<br><br>- Yes<br>- No                                                                                                                                                                                                                       |
| 9. Do you agree that your contributions are well received in OSS Communities?                                     | Closed question with options:<br><br>- Strongly Agree<br>- Agree<br>- Neutral<br>- Disagree<br>- Strongly Disagree                                                                                                                                                       |
| 10. Have you ever felt that one of your contributions was not well received due to your gender?                   | Closed question with options:<br><br>- Yes<br>- No                                                                                                                                                                                                                       |
| 11. How often do you feel that your contributions were not well received due to your gender?                      | Closed question with options:<br><br>- Never<br>- Sometimes<br>- Frequently                                                                                                                                                                                              |
| 12. Do you think it is important to have gender diversity in OSS Communities?                                     | Closed question with options:<br><br>- Very Important<br>- Important<br>- Moderately Important<br>- Slightly Important<br>- Not Important                                                                                                                                |
| 13. What is your suggestion to increase women's participation in the OSS Communities?                             | Open-ended question                                                                                                                                                                                                                                                      |
| 14. In your opinion, how to create a more inclusive environment for women in OSS Communities?                     | Open-ended question                                                                                                                                                                                                                                                      |
| 15. In your opinion, what are the reasons that motivate women to contribute to the OSS Communities?               | Open-ended question                                                                                                                                                                                                                                                      |
| 16. In your opinion, are the use of engaging techniques relevant to attracting more women to OSS Communities?     | Closed question with options:<br><br>- Yes<br>- No                                                                                                                                                                                                                       |
| 17. Do you know about the current research on gender diversity in OSS Communities?                                | Closed question with options:<br><br>- Yes<br>- No                                                                                                                                                                                                                       |
| 18. How do you perceive the relevance of gender diversity research in OSS Communities?                            | Closed question with options:<br><br>- Very Important<br>- Important<br>- Moderately Important<br>- Slightly Important<br>- Not Important                                                                                                                                |