---
title: "Work Practices and Perceptions from Women Core Developers in OSS Communities"
author: "Edna Canedo, Rodrigo Bonifácio, Márcio Okimoto, Alexander Serebrenik, Gustavo Pinto, and Eduardo Monteiro"
date: "ESEM 2020"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Supplementary material

### TableSM2. Suggestion to create a more inclusive environment for women in open source communities**

| **ID** | **Opinion**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| ------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| P1     | I think women are doing great in OSS, just a little more recognition and appreciating will motivate them and encourage new women to step into OSS.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| P2     | Stop treating women developers as ``women developers'' and start treating them as developers.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| P3     | It should be inclusive for everyone, regardless of gender or other characteristics. Talk about it, raise awareness, psychology and self development has a lot to teach us.                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| P4     | Programs like Outreachy help a lot.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| P5     | Have more women members and mentors in organizations.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| P6     | OSS Communities should be inclusive not only for women, but for all (men, women, LGBT..., disabled, etc).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| P7     | Less men.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| P8     | Mentorship program at school level.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| P9     | Allowing gender diversity.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| P10    | Have a clear Code of Conducts and a way to report abuses to Community Managers. Avoid gender pronouns (e.g.: using "guys" is very common, and this gives an idea that it is assumed that contributors are mostly men), so moderating language would help.                                                                                                                                                                                                                                                                                                                                                                                |
| P11    | Educate men to behave properly.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| P12    | Have more diverse involvement and then more diverse people will want to join in. But you need that to start somewhere, it is a slow change but it is going in the right direction.                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| P13    | Establishing good communication.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| P14    | Promote more women to senior role, prevent incidents of man-explaining.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| P15    | Establish a code of conduct for OSS projects where feedback is encouraged to be empathetic, encouraging, and supportive of all contributions.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| P16    | Inspite of organizing exclusive women events, organize events that are equal for everyone.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| P17    | Incentive woman participation at all levels, if the OSS reference are most men this is a problem. Promote women contributions in the community.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| P18    | Get more of them to participate.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| P19    | If the family does not have a positive environment for woman, then start working with the family to change their way of thinking (very difficult when religion is part of the cause). Otherwise, let know the woman not to fear when contributing, she will be treated just like anyone else: good contribution then its accepted regardless of gender, political views or religion, country of origin, etc., bad contributions are not accepted regardless of gender, political views or religion, country of origin, etc.                                                                                                              |
| P20    | In the R community there are R-Ladies events - held by and for women. Girl only or (predominantly) events in general, could create an environment that suggests that girls and women are actually wanted to be included in the community. Going for gender balance and diversity in hackathons or other OSS events helps. It also helps to celebrate achievements and invite more women to keynote events.                                                                                                                                                                                                                               |
| P21    | I think OSS communities are quite inclusive but lack a minimum percentage of women contributors.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| P22    | We need to support women in educational programs environments more.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| P23    | Placing more women in leadership positions will encourage a more open and inclusive environment that would hopefully encourage more diverse participation.                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| P24    | A good code of conduct and a good admin is all you need.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| P25    | By motivating them to work on more issues and features.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| P26    | Some projects reserved for women.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| P27    | Don't focus so much on 'important' very basic packages (e.g. Numpy, Scipy) but more on the smaller ones, e.g. important only in a couple specific domains (like PySAL or geopandas). You are much more likely to encourage women participation here. You will not limit yourself to attract women that have a classical computer science background, but e.g. women in earth system sciences, who are also technically inclined but have not come into direct contact with e.g. software development. You open up the pool of women to reach out to and you eliminate the danger of the 'I do not have enough skills for that' thinking. |
| P28    | Meetups.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| P29    | Honestly, I wish I knew more about how to better support inclusivity.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| P30    | Increase projects such as outreachy.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| P31    | If OSS communities host overnight hackathons, make sure to provide more or less comfortable place to sleep.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| P32    | Have closed forums for women to talk about their experiences.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |