---
title: 'Work Practices and Perceptions from Women Core Developers in OSS Communities'
author: Edna Canedo, Rodrigo Bonifácio, Márcio Okimoto, Alexander Serebrenik, Gustavo Pinto, and Eduardo Monteiro
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=5, fig.height=5, fig.path='figures/', dev=c('png', 'pdf'))
require(quanteda)
require(sqldf)
require(readtext)
require(wordcloud)
require(xtable)
require(plotrix)
require(gdata)
require(lattice)
require(Hmisc)
require(reshape2)
require(slam)
require(SentimentAnalysis)
setwd(".")
```

## Script assessing the third research question

To answer RQ3, we use one dataset. 

   * prds: contains information about the pull requests from women key developers 
   
```{r load}
prds <- read.csv("../datasets/pr_female_.csv", head=T, sep=";")
colnames(prds)
nrow(prds)
```

   * How many distinct PRs

```{r distinct-prs}
nprs <- sqldf("select count(distinct pr_id) 
               from prds")

nprs
```

   * comment distibution 
   
```{r comment-distribution}

cmt_by_pr <- sqldf("select pr_id, count(*) as total 
                    from prds 
                    group by pr_id")

summary(cmt_by_pr$total)
```

   * authorship (that is, how many key developers started the PRs)
   
```{r authorship,fig.width=8, fig.height = 3.5}
authorship <- sqldf("select login, count(distinct pr_id) as total 
                     from prds 
                     group by login")

nrow(authorship)
summary(authorship$total)
sd(authorship$total)
bwplot(authorship$total, xlab="Number of pull requests")
```

   * Conducting the sentiment analysis 
   
```{r}
# write.csv(stringi::stri_trans_general(gsub("[\r\n]", "", gsub("[[:punct:]]", "", prds$body)),"latin-ascii"), 
#    file="~/Documents/workspace-java/SentiSE/comments.csv",row.names=FALSE)
```